<map id="openage::pyinterface::PyException::type_name" name="openage::pyinterface::PyException::type_name">
<area shape="rect" id="node1" title=" " alt="" coords="5,71,181,112"/>
<area shape="rect" id="node2" href="$classopenage_1_1pyinterface_1_1_py_object_ref.xhtml#a912e76dc7854f9c1816533f6f8571767" title=" " alt="" coords="239,5,413,47"/>
<area shape="rect" id="node3" href="$classopenage_1_1pyinterface_1_1_py_object_ref.xhtml#afd545e1817cad9ab9f5c84934d83e428" title=" " alt="" coords="233,71,419,112"/>
<area shape="rect" id="node4" href="$namespaceopenage_1_1testing_1_1testing.xhtml#ac25bf81db406af62d08113ef7ae9fd6e" title=" " alt="" coords="229,137,423,163"/>
<area shape="rect" id="node5" href="$namespaceopenage_1_1util.xhtml#a7bc4421a5f0f57f3a0aba3f96eb8d19c" title=" " alt="" coords="471,137,597,163"/>
</map>
