<map id="openage::pyinterface::PyException" name="openage::pyinterface::PyException">
<area shape="rect" id="node1" title=" " alt="" coords="163,1435,305,1541"/>
<area shape="rect" id="node2" href="$classopenage_1_1error_1_1_error.xhtml" title=" " alt="" coords="5,1141,185,1335"/>
<area shape="rect" id="node3" title=" " alt="" coords="25,920,123,997"/>
<area shape="rect" id="node4" href="$structopenage_1_1log_1_1message.xhtml" title=" " alt="" coords="148,876,333,1041"/>
<area shape="rect" id="node5" href="$structopenage_1_1log_1_1level.xhtml" title=" " alt="" coords="176,736,305,813"/>
<area shape="rect" id="node6" href="$classopenage_1_1util_1_1_enum.xhtml" title=" " alt="" coords="339,419,486,687"/>
<area shape="rect" id="node7" href="$structopenage_1_1log_1_1level__value.xhtml" title=" " alt="" coords="217,264,347,356"/>
<area shape="rect" id="node8" href="$classopenage_1_1util_1_1_enum_value.xhtml" title=" " alt="" coords="197,5,367,215"/>
<area shape="rect" id="node9" href="$classopenage_1_1pyinterface_1_1_py_object_ref.xhtml" title=" " alt="" coords="209,1104,352,1372"/>
</map>
